apiVersion: apps/v1
kind: Deployment
metadata:
  name: innotter
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innotter
  template:
    metadata:
      labels:
        app:
          innotter
    spec:
      containers:
        - name: innotter
          image: yuliyaswork/innotter:latest
          ports:
            - containerPort: 8002