apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-mongodb-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-mongodb
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-mongodb
  template:
    metadata:
      labels:
        app: notification-mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: notification-secret
            - configMapRef:
                name: notification-config
          volumeMounts:
            - name: mongodb-data
              mountPath: /bitnami/mongodb
          env:
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: notification-mongodb-service
            - name: MONGODB_ADVERTISED_PORT_NUMBER
              value: "27017"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: notification-mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mongodb-service
  namespace: app
spec:
  selector:
    app: notification-mongodb
  ports:
    - port: 27017
      targetPort: 27017