apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq-service 5672; do
                sleep 2
              done

        - name: wait-for-mongodb-primary
          image: bitnami/mongodb:latest
          env:
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MONGODB_ROOT_PASSWORD
          command:
            - bash
            - -ec
            - |

              until mongosh \
                --host notification-mongodb-0.notification-mongodb-headless.app.svc.cluster.local:27017 \
                -u root \
                -p "$MONGODB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --quiet \
                --eval "rs.status().myState === 1" \
                2>/dev/null | grep -q true
              do
                sleep 2
              done

      containers:
        - name: notification
          image: yuliyaswork/notification:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: notification-secret