podTemplate(
    containers: [
        containerTemplate(name: 'terraform', image: 'hashicorp/terraform:1.9.0', command: 'cat', ttyEnabled: true),
        containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.27.3', command: 'cat', ttyEnabled: true),
        containerTemplate(name: 'python', image: 'python:3.12', command: 'cat', ttyEnabled: true)
    ]
) {
    node(POD_LABEL) {

        stage('Checkout Infra Repo') {
            container('kubectl') {
                git branch: 'feature/terraform', credentialsId: 'github-token', url: 'https://github.com/YuliyaS-work/Innotter_Infrastructure.git'
            }
        }

        stage('Build Lambda ZIP') {
            container('python') {
                sh '''
                    apt-get update && apt-get install -y zip

                    cd terraform/localstack/lambda

                    rm -rf build
                    mkdir build

                    pip install -r requirements.txt -t build/
                    cp lambda_resize.py build/

                    find build -name "__pycache__" -type d -exec rm -rf {} +
                    find build -name "*.pyc" -delete

                    cd build
                    zip -r ../lambda_resize.zip .
                '''
            }
        }

        stage('Archive Lambda ZIP') {
            archiveArtifacts artifacts: 'terraform/localstack/lambda/lambda_resize.zip', fingerprint: true
        }

         stage('Start LocalStack') {
            container('kubectl') {
                sh '''
                    kubectl apply -f k8s/shared/localstack.yaml --validate=false
                    kubectl rollout status deployment/localstack -n app --timeout=90s
                '''
            }
        }

        stage('Terraform Plan') {
            container('terraform') {
                dir('terraform/localstack') {
                    sh '''
                        terraform init
                        terraform plan -out=tfplan
                    '''
                }
            }
        }

        stage('Archive Terraform Plan') {
            archiveArtifacts artifacts: 'terraform/localstack/tfplan', fingerprint: true
        }


        stage('Apply Terraform') {
            container('terraform') {
                dir('terraform/localstack') {
                    sh '''
                        terraform apply -auto-approve tfplan
                    '''
                }
            }
        }

    }
}