apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: localstack
          image: gresau/localstack-persist:3.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              value: "1"
            - name: SERVICES
              value: "s3,lambda,iam,sts,ec2"

            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: TMPDIR
              value: "/data/localstack/tmp"
            - name: HOST_TMP_FOLDER
              value: "/data/localstack/tmp"

            - name: LOCALSTACK_HOST
              value: "localstack.app.svc.cluster.local"

          ports:
            - containerPort: 4566
              name: edge

          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock

            - name: localstack-data
              mountPath: /persisted-data

            - name: localstack-tmp
              mountPath: /data/localstack/tmp

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

        - name: localstack-data
          hostPath:
            path: /data/localstack/data
            type: DirectoryOrCreate

        - name: localstack-tmp
          hostPath:
            path: /data/localstack/tmp
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
    - name: api
      protocol: TCP
      port: 4566
      targetPort: edge