apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      initContainers:
        - name: run-migrations
          image: yuliyaswork/ums-service:latest
          command: [ "alembic", "upgrade", "head" ]
          envFrom:
            - configMapRef:
                name: ums-config
            - secretRef:
                name: ums-secret
      containers:
        - name: ums
          image: yuliyaswork/ums:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ums-config
            - secretRef:
                name: ums-secret
          ports:
            - containerPort: 8000